# Generated by Django 4.1.1 on 2022-10-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('KYCData', '0002_delete_pan'),
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('fname', models.CharField(max_length=122)),
                ('gender', models.CharField(max_length=122)),
                ('id_no', models.CharField(max_length=122)),
                ('dob', models.CharField(max_length=122)),
                ('id_type', models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='doc/pan/')),
            ],
        ),
    ]
