# Generated by Django 4.1.1 on 2022-10-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KYCData', '0006_alter_image_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='image',
        ),
        migrations.AddField(
            model_name='details',
            name='img',
            field=models.BooleanField(default=True),
        ),
    ]
